#!/usr/bin/env python3

import os
import json
import saxo

url = "https://montanaflynn-spellcheck.p.mashape.com/check/?text="
apikey = ""

@saxo.command()
def number(arg):

	argurl = arg.replace(' ', "%20")
	checkUrl = url + argurl 
	page = saxo.request(checkUrl, headers={"X-Mashape-Key": apikey, "Accept": "text/plain"})
	data = json.loads(page["text"])
	correction = data["suggestion"]
	if correction == arg:	
		return "I think you spelled that correctly."
	return "I suggest: " + correction
	
