#!/usr/bin/env python3

import os
import json
import saxo

url = "https://numbersapi.p.mashape.com/"
apikey = ""

@saxo.command()
def number(arg):

	mathUrl = url + arg + '/math?fragment=true&json=true'
	triviaUrl = url + arg + '/trivia?fragment=true&json=true'
	page = saxo.request(mathUrl, headers={"X-Mashape-Key": apikey, "Accept": "text/plain"})
	data = json.loads(page["text"])
	if not data["found"]:
		return "No entry found."
	mathText = arg + " is " + data["text"]
	page = saxo.request(triviaUrl, headers={"X-Mashape-Key": apikey, "Accept": "text/plain"})
	data = json.loads(page["text"])
	fullText = mathText + ". It is also " + data["text"] + "."
	return fullText
